title: Committed to Memory
email: jacoby.david@live.com
description: > # this means to ignore newlines until "baseurl:"
    Dave writes code. Sometimes this means he learns something. 
    He'll probably write it up here.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacoby.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jacobydave
github_username:  jacoby

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


